#!/usr/bin/env python3
"""Regression-check normscreen against the audit's own frozen census.

This takes the frozen per-dataset minimum variances from the audit's benchmark map --
machine-generated by repro-harness/scripts/assemble_map.py, not obtained by hand -- and
checks that normscreen's floor_share reproduces the stored shares exactly at the six
significant figures they are stored to. It also round-trips the real per-window variances
of the checkpoint-audited datasets through the screen.

WHAT THIS IS NOT. normscreen.floor_share and assemble_map.py evaluate the same expression,
eps/(Var+eps). This suite therefore cannot validate the statistic; it binds the released
screen and the stored census together so that a change in either goes red. It takes the
variance extraction as given. An earlier version of this docstring also claimed the suite
checked conditioning BANDS against the paper's categories -- it never did, and the claim is
removed rather than left describing a check that does not run.

Run:  python3 test_against_paper.py
"""
import glob
import gzip
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from normscreen import band_for, floor_share  # noqa: E402


def _find_fixtures() -> str:
    """Locate the audit's frozen fixtures from either checkout layout.

    The instrument ships inside the harness repository but is also developed
    beside it, so ``fixtures/`` sits either in this directory's parent or one
    level further up. Search rather than hard-code, and fail loudly if absent:
    a missing fixture tree must not silently degrade this suite into a
    zero-check pass.
    """
    probe = os.path.join("fixtures", "generalization", "benchmark_map", "MAP.json")
    d = HERE
    for _ in range(4):
        for base in (d, os.path.join(d, "repro-harness")):
            if os.path.exists(os.path.join(base, probe)):
                return os.path.join(base, "fixtures")
        # Stop at the harness root. Without this the search walks out of the repository
        # and can silently bind to an unrelated tree that happens to hold a census -- the
        # suite then reports green while validating a checkout nobody shipped.
        if os.path.exists(os.path.join(d, "verify.py")) or \
           os.path.exists(os.path.join(d, "MANIFEST.md")):
            break
        d = os.path.dirname(d)
    raise SystemExit(
        "cannot locate the audit fixtures (fixtures/generalization/benchmark_map/"
        "MAP.json) above " + HERE + ". This suite validates the screen against the "
        "audit's frozen census; without the fixtures it verifies nothing, so it "
        "fails rather than reporting a pass."
    )


FIXTURES = _find_fixtures()
MAP = os.path.join(FIXTURES, "generalization", "benchmark_map", "MAP.json")
RB = os.path.join(FIXTURES, "rb_models")
EPS_LIB = 1e-7
# The census sizes quoted in README.md and in the paper. Pinned so a truncated or
# partially-fetched fixture tree fails instead of passing on a subset.
EXPECT_MAP_ROWS = 17
EXPECT_RB_WINDOWS = 1728
EXPECT_RB_DETERMINED = 688   # windows with floor share >= 0.90 (the reported 39.8%)
# RELATIVE tolerance. An absolute 5e-6 would accept a row whose stored share is 8e-6 at
# any value below 1.3e-5 -- i.e. barely one significant figure -- while the claim being
# made is agreement to the printed precision. Relative tolerance means the claim and the
# check are the same statement.
TOL = 5e-6


def check_map() -> tuple[int, int, int]:
    with open(MAP, encoding="utf-8") as f:
        m = json.load(f)
    rows = m["rows"] if isinstance(m, dict) and "rows" in m else m
    ok = bad = exact = 0
    print(f"{'dataset':38s} {'min Var':>11}  {'paper':>9}  {'normscreen':>10}  band")
    for r in rows:
        mv, paper = r.get("min_var"), r.get("floor_share_epslib")
        if mv is None or paper is None:
            continue
        got = float(floor_share(mv, EPS_LIB))
        exact += (float(f"{got:.6g}") == paper)
        rel = abs(got - paper) / abs(paper) if paper else abs(got)
        agree = rel <= TOL
        ok, bad = (ok + 1, bad) if agree else (ok, bad + 1)
        print(f"{r['dataset'][:38]:38s} {mv:11.3e}  {paper:9.6f}  {got:10.6f}  "
              f"{band_for(got):18s}{'' if agree else '   <-- MISMATCH'}")
    return ok, bad, exact


def check_exact_at_stored_precision(exact: int, n: int) -> int:
    """Assert every row is reproduced EXACTLY at the precision the fixture stores.

    This replaces an earlier check that asserted a "worst-case relative agreement" of
    3.715e-6 against the number table. That figure was not an agreement: assemble_map.py
    stores eps/(Var+eps) at %.6g and normscreen computes the same expression, so the
    quantity being reported was the storage rounding of the single tightest row, and would
    have been 0.0 had the fixture stored full precision. Worse, the value it was compared
    against lived in the same fixture tree that supplies MAP.json, so the two moved in
    lockstep and the "pin" could not detect the drift it advertised.

    Exact-at-stored-precision is the honest form: it is a true binary property, it goes red
    on any real change to either side, and it claims nothing about independence.
    """
    ok = (exact == n and n > 0)
    print(f"  {exact}/{n} rows reproduced exactly at the stored precision "
          f"({'OK' if ok else 'MISMATCH'})")
    return 0 if ok else 1


def check_rb_windows() -> tuple[int, int]:
    """Feed the real per-window target variances through the screen."""
    rows = []
    for fp in sorted(glob.glob(os.path.join(RB, "*.json.gz"))):
        with gzip.open(fp, "rt", encoding="utf-8") as f:
            rows += json.load(f)["rows"]
    if len(rows) != EXPECT_RB_WINDOWS:
        print(f"  FAIL: expected {EXPECT_RB_WINDOWS} windows under {RB}, found {len(rows)}")
        return 0, 1
    var = np.array([min(r["target_variance_ddof1"]) for r in rows], dtype=np.float64)
    shares = np.asarray(floor_share(var, EPS_LIB))
    dominated = int(np.sum(shares >= 0.90))
    worst = float(shares.max())
    print(f"  {len(rows)} Rayleigh-Benard windows, least-conditioned field per window")
    print(f"  worst floor share {worst:.6f} ({band_for(worst)})")
    print(f"  floor-determined (share>=0.90) in {dominated}/{len(rows)} windows "
          f"({100*dominated/len(rows):.1f}%)")
    # Assert the claim the paper actually makes (>=0.9999), not a decade looser. At the
    # previous >=0.99 threshold a ~110x error in the packaged variances still passed. The
    # floor-determined count is pinned too, so the reported 39.8% cannot drift silently.
    agree = worst >= 0.9999 and dominated == EXPECT_RB_DETERMINED
    print(f"  agrees with the paper's floor-determined verdict: {agree}"
          f"{'' if agree else f' (worst={worst:.6f}, determined={dominated}, expected {EXPECT_RB_DETERMINED})'}")
    return (1, 0) if agree else (0, 1)


if __name__ == "__main__":
    print("=== normscreen vs the audit's frozen benchmark map ===")
    print(f"fixture tree: {FIXTURES}\n")
    ok1, bad1, exact1 = check_map()
    print(f"\n  {ok1} rows agree, {bad1} disagree (tolerance {TOL:g})")
    if ok1 + bad1 != EXPECT_MAP_ROWS:
        print(f"  FAIL: expected {EXPECT_MAP_ROWS} comparable rows in MAP.json, "
              f"got {ok1 + bad1}")
        bad1 += 1
    bad1 += check_exact_at_stored_precision(exact1, ok1 + bad1)
    print()
    print("=== normscreen on the real per-window variances ===")
    ok2, bad2 = check_rb_windows()
    bad = bad1 + bad2
    print("\n" + ("PASS: the instrument reproduces the audit's conditioning numbers."
                  if not bad else f"FAIL: {bad} disagreement(s)."))
    raise SystemExit(1 if bad else 0)
